(function () {
const WIDTH = 1180;
const HEIGHT = 760;

const COLORS = {
  ink: 0x3e2b22,
  paper: 0xfff4dc,
  violet: 0x77559a,
  berry: 0xa54762,
  green: 0x6c9b77,
  teal: 0x3f817a,
  gold: 0xf0bd4e,
  clay: 0xb8784a,
  cream: 0xfff8e9,
  softBlue: 0x8ab7c6,
};

const LAYOUT = {
  book: { x: WIDTH / 2, y: HEIGHT / 2, width: WIDTH, height: HEIGHT },
  pageTurn: { x: WIDTH / 2 + 20, y: 378, scale: 2.04, frameDelay: 105 },
  rosarito: { x: 1010, y: 458, scale: 0.38 },
  progress: {
    x: 825,
    y: 96,
    size: 54,
    spacing: 90,
    total: 3,
    inactiveTint: 0xd0c2b0,
    inactiveAlpha: 0.58,
    starKey: "ui-star_full",
  },
  base: {
    audioButton: { x: 56, y: 690, key: "ui-button_audio", width: 82, height: 82, depth: 10 },
    grass: { x: 52, y: 86, key: "ui-grass_large", scale: 0.64, alpha: 0.92, depth: 3 },
    nextButton: { x: 1098, y: 675, width: 250, labelX: -163, labelY: 13, enabled: true },
    title: {
      x: 112,
      y: 70,
      maxWidth: 450,
      maxHeight: 56,
      minFontSize: 26,
      fontSize: "34px",
      color: "#3e2b22",
      stroke: "#f6e2ba",
      strokeThickness: 3,
    },
    subtitle: {
      x: 112,
      y: 128,
      maxWidth: 430,
      maxHeight: 64,
      minFontSize: 16,
      fontSize: "22px",
      color: "#5d4437",
      lineSpacing: 8,
      wordWrap: 430,
    },
  },
};

const PAGE_AREAS = {
  left: { x: 54, y: 54, width: 520, height: 650 },
  right: { x: 606, y: 54, width: 520, height: 650 },
  gutter: { x: 566, y: 54, width: 48, height: 650 },
  safe: { x: 70, y: 70, width: 1040, height: 620 },
};

const SCENE_LAYOUTS = {
  cover: {
    rosarito: { x: 214, y: 516, scale: 0.6, depth: 8 },
    shadow: { x: 214, y: 678, width: 190, height: 34, color: 0x5b3f2d, alpha: 0.18, depth: 2 },
    missions: [
      { label: "Infancia", icon: "ui-icon_question", scene: "QuizGame", order: 1 },
      { label: "Puzzle", icon: "ui-icon_puzzle", scene: "PuzzleGame", order: 2 },
      { label: "Objetos", icon: "ui-icon_ink", scene: "ObjectsGame", order: 3 },
    ],
    title: [
      { x: 205, y: 82, text: "La aventura de", fontSize: "38px", origin: 0 },
      { x: 205, y: 124, text: "Rosarito", fontSize: "78px", origin: 0, strokeThickness: 5 },
    ],
    titleDivider: { x: 344, y: 246, width: 230, height: 52, depth: 4 },
    titleFlowers: [
      { x: 150, y: 160, key: "ui-flower_cluster_left", width: 120, height: 78, angle: -8, depth: 4 },
      { x: 407, y: 166, key: "ui-flower_cluster_bottom", width: 146, height: 96, angle: 5, depth: 4 },
    ],
    narrative: {
      x: 448,
      y: 356,
      text: "Ayuda a Rosarito a aprender, jugar y recordar su historia.",
      options: {
        key: "m2-speech_narrative",
        width: 324,
        height: 166,
        depth: 6,
        textOffsetX: 6,
        textOffsetY: -8,
        maxWidth: 226,
        maxHeight: 86,
        fontSize: "20px",
        minFontSize: 17,
      },
    },
    narrativeHeart: {
      x: 420,
      y: 372,
      key: "m2-heart",
      width: 28,
      height: 26,
      depth: 8,
    },
    mouseHint: {
      x: 452,
      y: 574,
      text: "Usa el mouse\npara explorar.",
      options: {
        key: "m2-speech_mouse",
        width: 246,
        height: 172,
        depth: 6,
        textOffsetY: -30,
        iconOffsetY: 50,
        iconSize: 50,
        maxWidth: 158,
        maxHeight: 60,
        fontSize: "19px",
        minFontSize: 16,
      },
    },
    rightDecorationBottom: { x: 650, y: 666, key: "ui-flower_cluster_bottom", width: 150, height: 96, depth: 5 },
    leftDecorationBottom: { x: 90, y: 450, key: "ui-flower_cluster_left", width: 96, height: 58, angle: -18, depth: 4 },
    startButton: { x: 1010, y: 706, width: 280, depth: 10 },
    starCounter: { x: 1130, y: 90 },
    missionHeader: {
      badge: { x: 860, y: 112, key: "ui-speech_large_lilac", width: 300, height: 98, depth: 5 },
      title: {
        x: 860,
        y: 112,
        text: "Tu misión",
        maxWidth: 220,
        maxHeight: 52,
        minFontSize: 34,
        depth: 6,
        style: { fontSize: "42px", fontStyle: "bold", color: "#6a3d8f", align: "center" },
      },
    },
    missionSummary: {
      bg: { x: 860, y: 232, key: "ui-speech_large_cream", width: 440, height: 138, alpha: 0.9, depth: 4 },
      title: {
        x: 860,
        y: 226,
        text: "Completa las actividades para conocer la vida y el legado de Rosarito.",
        maxWidth: 340,
        maxHeight: 86,
        minFontSize: 18,
        depth: 5,
        style: { fontSize: "22px", wordWrap: { width: 340 } },
      },
      icon: { x: 860, y: 298, key: "ui-icon_heart", width: 34, height: 34, depth: 5 },
      titleBadge: {
        x: 846,
        y: 570,
        text: "Gran objetivo",
        maxWidth: 210,
        maxHeight: 48,
        minFontSize: 20,
        depth: 5,
        style: { fontSize: "26px", fontStyle: "bold", color: "#6a3d8f", align: "center" },
      },
      description: {
        x: 848,
        y: 615,
        text: "Completa las actividades y gana el Álbum de Rosarito.",
        maxWidth: 235,
        maxHeight: 54,
        minFontSize: 15,
        depth: 5,
        style: { fontSize: "17px", wordWrap: { width: 235 } },
      },
    },
    missionCards: { x: 705, y: 430, gap: 180 },
    startButtonLabel: "Comenzar",
    missionCard: {
      bg: { key: "ui-card_arch_filled", width: 138, height: 164 },
      badge: { key: "ui-icon_flower", x: -50, y: -70, width: 52, height: 52 },
      numberText: {
        x: -50,
        y: -72,
        show: false,
        fontSize: "22px",
        fontStyle: "bold",
        color: "#fff8e9",
        align: "center",
        origin: 0.5,
        offsetY: 0,
      },
      icon: { x: 0, y: -24, width: 74, height: 64 },
      labelText: {
        x: 0,
        y: 40,
        fontSize: "15px",
        fontStyle: "bold",
        color: "#3e2b22",
        align: "center",
        wordWrap: 112,
        lineSpacing: 0,
        maxWidth: 112,
        maxHeight: 52,
      },
      cardHeight: 224,
      baseOffsetY: 8,
      interactiveWidth: 138,
      interactiveHeight: 170,
      hoverScale: 1.04,
    },
    goalPanel: {
      x: 858,
      y: 605,
      key: "ui-notebook_panel",
      width: 420,
      height: 144,
      depth: 4,
      book: { x: 708, y: 606, key: "ui-icon_book", width: 84, height: 72, depth: 5 },
      star: { x: 1014, y: 605, key: "ui-star_full", width: 80, height: 80, depth: 5 },
    },
    startButtonDecoration: {
      arrow: { x: 1120, y: 706, key: "ui-icon_arrow_right", width: 48, height: 42, depth: 11 },
      flower: { x: 1088, y: 685, key: "ui-flower_cluster_bottom", width: 86, height: 58, depth: 11 },
    },
  },
  dones: {
    optionStart: { x: 735, y: 330 },
    optionGap: { x: 240, y: 132 },
    rosarito: { x: 1082, y: 595, scale: 0.19 },
    choiceCard: {
      bgKey: "ui-panel_task_floral",
      bgWidth: 230,
      bgHeight: 86,
      width: 230,
      height: 86,
      padding: 22,
      textStyle: {
        fontSize: "23px",
        color: "#4a3026",
        align: "center",
        wordWrap: { width: 208 },
      },
      hoverScale: 1.03,
      minFontSize: 12,
      maxTextHeight: 58,
      iconOffsetY: 0,
    },
    componentCard: {
      bgKey: "m1-minigame1_update2_04",
      width: 230,
      height: 110,
      iconKeyFallback: "m1-minigame1_update2_07",
      iconX: 18,
      iconY: -26,
      iconWidth: 44,
      iconHeight: 44,
      label: {
        x: 18,
        y: 27,
        maxWidth: 160,
        maxHeight: 44,
        minFontSize: 12,
        fontSizeLong: "17px",
        fontSizeMedium: "19px",
        fontSizeShort: "22px",
        breakpoints: [30, 20],
        color: "#3e2b22",
        align: "center",
        wordWrap: { width: 160 },
      },
      hoverScale: 1.04,
      interactiveWidth: 230,
      interactiveHeight: 86,
    },
  },
  quiz: {
    starCounter: { x: 1130, y: 82 },
    feedback: {
      correct: "Respuesta correcta",
      incorrect: "Probemos otra vez",
    },
    rosarito: { x: 190, y: 465, scale: 0.48, depth: 8 },
    shadow: { x: 190, y: 650, width: 150, height: 28, color: 0x5b3f2d, alpha: 0.18, depth: 2 },
    leftPanel: {
      x: 355,
      y: 462,
      key: "minigame2-left-bg",
      width: 440,
      height: 350,
      depth: 3,
      alpha: 0.94,
      titleHeart: {
        x: 414,
        y: 415,
        key: "m2-heart",
        width: 28,
        height: 26,
        depth: 8,
      },
    },
    title: [
      { x: 210, y: 72, text: "La infancia de", fontSize: "40px", origin: 0 },
      { x: 210, y: 124, text: "Rosario", fontSize: "82px", origin: 0, strokeThickness: 5 },
    ],
    titleDivider: { x: 345, y: 238, width: 230, height: 52 },
    titleFlowers: [
      { x: 145, y: 145, key: "ui-flower_cluster_left", width: 105, height: 68, angle: -8 },
      { x: 465, y: 145, key: "ui-flower_cluster_bottom", width: 118, height: 78 },
    ],
    narrative: {
      x: 410,
      y: 338,
      text: "Cuando Rosarito era niña, vivió momentos especiales que la ayudaron a soñar en grande.",
      options: {
        key: "m2-speech_narrative",
        width: 244,
        height: 168,
        depth: 7,
        textOffsetX: 4,
        textOffsetY: -11,
        maxWidth: 178,
        maxHeight: 118,
        fontSize: "16px",
        minFontSize: 15,
        lineSpacing: 2,
      },
    },
    mouseHint: {
      x: 355,
      y: 610,
      text: "Usa el mouse para elegir la respuesta correcta.",
      options: {
        key: "m2-speech_mouse",
        width: 205,
        height: 148,
        depth: 7,
        textOffsetY: -28,
        iconOffsetY: 40,
        iconSize: 48,
        maxWidth: 132,
        maxHeight: 72,
        fontSize: "16px",
        minFontSize: 15,
      },
    },
    headerQuestion: {
      title: "Responde y aprende",
      x: 884,
      y: 92,
      width: 390,
      height: 70,
      fontSize: "28px",
      color: "#6a3d8f",
      heart: false,
      depth: 5,
    },
    headerInstruction: {
      title: "Haz clic en la respuesta correcta.",
      x: 884,
      y: 188,
      width: 430,
      height: 62,
      fontSize: "21px",
      color: "#3e2b22",
      maxWidth: 350,
      heart: false,
      depth: 4,
    },
    questionPanel: {
      x: 884,
      y: 310,
      panelWidth: 470,
      panelHeight: 78,
      panelDepth: 5,
      panelKey: "m2-question_panel",
      flowerKey: "ui-icon_flower",
      flowerSize: 74,
      badgeXOffset: -234,
      badgeY: -8,
      counterXOffset: 222,
      counterYOffset: -3,
      counterWidth: 78,
      counterHeight: 48,
      questionMaxWidth: 352,
      questionMaxHeight: 68,
      questionMinFontSize: 17,
      questionFontSize: "22px",
      questionLongFontSize: "20px",
      maxQuestionLength: 52,
      progressFontSize: "22px",
      correctMark: {
        x: 58,
        y: -104,
        key: "ui-icon_check",
        width: 42,
        height: 42,
      },
      heartOffsetY: 0,
    },
    answerStart: { x: 735, y: 526 },
    answerGap: 176,
    answerCard: {
      cardWidth: 118,
      cardHeight: 224,
      iconSize: { x: 0, y: -52, width: 70, height: 58 },
      textPos: { x: 0, y: 58, maxWidth: 96, maxHeight: 70, width: 104 },
      textStyle: {
        fontSizeLarge: "17px",
        fontSizeSmall: "16px",
        lineSpacing: 4,
        align: "center",
        color: "#4a3026",
      },
      heart: { x: 0, y: 110, width: 30, height: 28 },
      cardKeys: ["m2-answer_card_green", "m2-answer_card_blue", "m2-answer_card_pink"],
      iconFallbackKeys: ["ui-icon_home", "ui-icon_blackboard", "ui-icon_flower"],
      fontSizeThreshold: 18,
      hoverScale: 1.04,
    },
    questionDecor: {
      sideLeaf: {
        x: 1142,
        y: 140,
        key: "m2-leaves",
        width: 70,
        height: 48,
        angle: 16,
        depth: 3,
      },
      leftPlant: {
        x: 1100,
        y: 646,
        key: "ui-plant_lavender",
        width: 46,
        height: 96,
        depth: 3,
      },
      rightPlant: {
        x: 1150,
        y: 642,
        key: "ui-plant_pink",
        width: 56,
        height: 98,
        depth: 3,
      },
    },
  },
  puzzle: {
    starCounter: { x: 1130, y: 84 },
    feedback: {
      correct: "¡Imagen completa!",
      incorrect: "Casi! Mira la guía y prueba otra vez.",
    },
    rosarito: { x: 170, y: 480, scale: 0.48, depth: 8 },
    shadow: { x: 170, y: 650, width: 142, height: 26, color: 0x5b3f2d, alpha: 0.18, depth: 2 },
    noPuzzle: {
      text: "Agrega imágenes en assets/puzzles/source para jugar.",
      x: 590,
      y: 360,
      options: {
        maxWidth: 640,
        maxHeight: 100,
        minFontSize: 20,
        style: {
          fontSize: "28px",
          color: "#3e2b22",
          align: "center",
          wordWrap: { width: 640 },
        },
      },
    },
    topLabel: {
      badge: { x: 370, y: 94, key: "ui-label_long_cream", width: 164, height: 52, tint: 0x8c63a8, alpha: 0.86, depth: 4 },
      text: { x: 370, y: 94, text: "Juego 2", maxWidth: 130, maxHeight: 50, minFontSize: 18, depth: 5, style: { fontSize: "26px", fontStyle: "bold", color: "#fff8e9" } },
    },
    title: [
      { x: 352, y: 142, text: "El rompecabezas", fontSize: "43px" },
      { x: 365, y: 205, text: "de Rosario", fontSize: "48px" },
    ],
    titleDivider: { x: 402, y: 256, width: 235, height: 50 },
    titleFlowers: [
      { x: 156, y: 154, key: "ui-flower_cluster_left", width: 76, height: 54, angle: -8 },
      { x: 505, y: 174, key: "ui-flower_cluster_bottom", width: 92, height: 58 },
    ],
    narrative: {
      x: 408,
      y: 340,
      text: "¡Vamos a armar la imagen de Rosario Vera Peñaloza!",
      options: {
        key: "m2-speech_narrative",
        width: 300,
        height: 132,
        depth: 7,
        textOffsetX: 6,
        textOffsetY: -4,
        maxWidth: 220,
        maxHeight: 78,
        fontSize: "23px",
        minFontSize: 18,
      },
    },
    mouseHint: {
      x: 430,
      y: 515,
      text: "Arrastra cada pieza al lugar correcto.",
      options: {
        key: "m2-speech_lilac",
        width: 292,
        height: 166,
        depth: 8,
        textOffsetY: -23,
        iconOffsetY: 59,
        iconSize: 46,
        maxWidth: 176,
        maxHeight: 64,
        fontSize: "18px",
        minFontSize: 15,
      },
    },
    infoDecor: {
      flower: {
        x: 510,
        y: 650,
        key: "ui-icon_flower",
        width: 40,
        height: 40,
        depth: 7,
      },
    },
    infoPanel: {
      x: 275,
      y: 648,
      width: 360,
      height: 116,
      previewX: 174,
      previewY: 644,
      previewWidth: 118,
      previewHeight: 82,
      labelPanel: {
        x: 356,
        y: 606,
        width: 150,
        height: 46,
        tint: 0x8c63a8,
        depth: 6,
        title: "De su vida real",
        textMaxWidth: 132,
        textMaxHeight: 36,
        textMinFontSize: 12,
        textStyle: {
          fontSize: "16px",
          fontStyle: "bold",
          color: "#fff8e9",
        },
      },
      titleX: 356,
      titleY: 656,
      titleMaxWidth: 168,
      titleMaxHeight: 56,
      titleStyle: {
        color: "#3e2b22",
        fontSize: "16px",
        fontStyle: "bold",
      },
      puzzleTextMaxWidth: 168,
      puzzleTextStyle: {
        fontSize: "15px",
        color: "#3e2b22",
      },
    },
    board: { x: 885, y: 365, size: 390 },
    boardStyle: {
      sizeColor: 0xb992d6,
      sizeAlpha: 0.78,
      frameThickness: 4,
      frameColor: 0x7c529a,
      frameAlpha: 0.95,
      innerThickness: 2,
      innerColor: 0xf0d1ff,
      innerAlpha: 0.76,
      boardRadius: 22,
      boardStrokeRadius: 22,
      previewAlpha: 0.22,
      fillColor: 0xf7e5c4,
      fillAlpha: 0.62,
      previewDepth: 5,
      frameDepth: 4,
      fillDepth: 4,
      boardPulse: {
        key: "ui-icon_sparkles",
        scale: 3.6,
        alphaTo: 0,
        duration: 360,
        targetScale: 3.6,
      },
      snapDistance: 78,
      dragHint: {
        key: "ui-icon_sparkles",
        size: 28,
        alpha: 0.4,
        depth: 16,
        activeDistance: 120,
        tint: 0xf0d5a0,
      },
      slotHint: {
        color: 0x6f3a90,
        alpha: 0.2,
        thickness: 2,
        radius: 28,
      },
      lockBadge: {
        key: "m2-heart",
        size: 26,
        sizeLarge: 24,
        alpha: 0.9,
        tint: 0x5ea57f,
      },
      sparkle: {
        key: "ui-icon_sparkles",
        size: 34,
        fadeDuration: 360,
        rise: 14,
      },
      slotLine: {
        color: 0xc99d68,
        alpha: 0.72,
        thickness: 3,
        radiusSmall: 25,
        radiusLarge: 24,
        leftArcOffsetX: 26,
        leftArcOffsetY: -28,
        rightArcOffsetX: -35,
        rightArcOffsetY: -23,
        topStopOffset: 54,
        middleStopOffset: 2,
        leftStopOffsetX: -62,
        rightStopOffsetX: 62,
      },
      slotLineOverlay: {
        color: 0xffffff,
        alpha: 0.48,
        thickness: 2,
      },
    },
    tray: {
      x: 660,
      y: 590,
      width: 470,
      height: 108,
      slotY: 54,
      slotSpacing: 102,
      slotCount: 4,
      slotMargin: 44,
      panel: {
        key: "ui-panel_task_floral",
        padding: 11,
        depth: 3,
        alpha: 0.82,
      },
      decor: {
        topLeftSparkle: {
          key: "ui-icon_sparkles",
          xOffset: 28,
          yOffset: 22,
          width: 28,
          height: 28,
          depth: 5,
          alpha: 0.7,
        },
        bottomRightFlower: {
          key: "ui-flower_cluster_bottom",
          xOffset: 436,
          yOffset: 84,
          width: 72,
          height: 42,
          depth: 5,
          alpha: 0.78,
        },
        bottomLeftLeaves: {
          key: "m2-leaves",
          xOffset: 24,
          yOffset: 86,
          width: 42,
          height: 30,
          depth: 5,
          angle: -8,
          alpha: 0.7,
        },
      },
      border: {
        color: 0xd8b17a,
        alpha: 0.86,
        thickness: 2,
        radius: 18,
        xPadding: 15,
        yPadding: 10,
        widthInset: 30,
        heightInset: 24,
      },
      slotBg: {
        fillColor: 0xfff6de,
        fillAlpha: 0.28,
        borderColor: 0xd6ad78,
        borderAlpha: 0.55,
        width: 88,
        height: 90,
        radius: 18,
        borderRadius: 14,
        glow: {
          key: "ui-icon_sparkles",
          size: 18,
          alpha: 0.22,
          tint: 0xf2cf9e,
        },
      },
    },
    header: {
      title: "Arma la imagen con las piezas.",
      x: 884,
      y: 128,
      width: 410,
      height: 66,
      fontSize: "23px",
      color: "#3e2b22",
      maxWidth: 340,
      heartOffsetY: 38,
      depth: 4,
      leaf: { x: 1140, y: 156, key: "m2-leaves", width: 72, height: 52, angle: 22, depth: 4 },
    },
    nextButton: { x: 1095, y: 675, label: "Siguiente" },
  },
  objects: {
    starCounter: { x: 1130, y: 84 },
    feedback: {
      complete: "Encontraste todos los objetos.",
      completeHint: "¡Qué bien! Rosario usaba estos objetos para enseñar con amor.",
    },
    shadow: { x: 170, y: 650, width: 142, height: 26, color: 0x5b3f2d, alpha: 0.18, depth: 2 },
    rosarito: { x: 150, y: 485, scale: 0.45, depth: 8 },
    title: [
      { x: 330, y: 72, text: "Los objetos de", fontSize: "42px" },
      { x: 360, y: 138, text: "Rosario", fontSize: "76px", strokeThickness: 5 },
    ],
    titleDivider: { x: 385, y: 208, width: 230, height: 50 },
    titleFlowers: [
      { x: 180, y: 105, key: "ui-flower_cluster_left", width: 82, height: 58, angle: -8 },
      { x: 520, y: 120, key: "ui-flower_cluster_bottom", width: 92, height: 60 },
    ],
    narrative: {
      x: 420,
      y: 294,
      text: "Encuentra los objetos que usaba Rosario en su misión de enseñar a muchos niños.",
      options: {
        width: 288,
        height: 150,
        depth: 7,
        textOffsetX: 2,
        textOffsetY: -8,
        maxWidth: 205,
        maxHeight: 94,
        fontSize: "19px",
        minFontSize: 16,
        lineSpacing: 3,
      },
    },
    mouseHint: {
      x: 185,
      y: 590,
      text: "Toca\nlos objetos.",
      options: {
        width: 196,
        height: 124,
        depth: 10,
        textOffsetY: -20,
        iconOffsetY: 36,
        iconSize: 42,
        maxWidth: 122,
        maxHeight: 46,
        fontSize: "18px",
        minFontSize: 14,
      },
    },
    header: {
      title: "Encuentra los objetos",
      x: 895,
      y: 92,
      width: 390,
      height: 70,
      color: "#5b3277",
      depth: 5,
      tint: 0xb994c7,
      fontSize: "28px",
      heartOffsetY: 45,
    },
    headerLeaf: {
      x: 1140,
      y: 145,
      key: "m2-leaves",
      width: 78,
      height: 56,
      angle: 18,
      depth: 4,
    },
    checklistFlowerBottom: {
      x: 560,
      y: 656,
      key: "ui-flower_cluster_bottom",
      width: 86,
      height: 54,
      depth: 6,
    },
    checklist: {
      x: 452,
      y: 536,
      panelWidth: 300,
      panelHeight: 316,
      headerWidth: 314,
      headerHeight: 92,
      headerY: 383,
      titleY: 392,
      title: "¿Puedes encontrarlos?",
      item: {
        startY: 456,
        spacing: 48,
        width: 266,
        height: 50,
        iconX: -104,
        iconW: 38,
        iconH: 38,
        labelX: -55,
        labelY: 0,
        labelMaxWidth: 148,
        labelMaxHeight: 42,
        labelMinFont: 12,
        labelStyle: {
          fontSize: "18px",
          color: "#3e2b22",
          wordWrap: { width: 148 },
          align: "left",
        },
        checkX: 112,
        checkSize: 30,
        checkTint: 0x4f8553,
      },
    },
    searchScene: {
      hitDefaults: {
        basePadding: 58,
        sizeScale: 0.1,
      },
      fills: {
        base: { color: 0xf6dfb6, alpha: 0.95 },
      },
      sceneFrame: { x: 630, y: 136, width: 544, height: 484, radius: 24 },
      frameBorder: {
        outer: { lineWidth: 5, color: 0xb990c7, alpha: 0.95 },
        inner: { lineWidth: 2, color: 0xf0d1ff, alpha: 0.76 },
      },
      inner: { x: 642, y: 148, width: 520, height: 460, radius: 18 },
      backgroundKey: "hidden-classroom",
      leaves: {
        left: { x: 675, y: 588, key: "ui-flower_cluster_bottom", width: 92, height: 58 },
        right: { x: 1138, y: 584, key: "ui-flower_cluster_left", width: 74, height: 62, angle: 14 },
      },
      successPanel: {
        x: 896,
        y: 626,
        depth: 850,
        boxKey: "ui-label_long_cream",
        boxWidth: 350,
        boxHeight: 80,
        heartX: -152,
        heartY: -2,
        heartKey: "m2-heart",
        heartWidth: 28,
        heartHeight: 26,
        messageX: 18,
        messageY: 0,
        messageMaxWidth: 285,
        messageMaxHeight: 66,
        messageLineSpacing: 2,
        messageFontSize: "18px",
        messageMinFont: 14,
        completeText: "¡Qué bien! Rosario usaba estos objetos para enseñar con amor.",
      },
      pulse: {
        key: "ui-icon_sparkles",
        size: 48,
        tint: 0xf2cf6e,
        depth: 24,
        alphaTo: 0.88,
        alphaFrom: 0,
        scaleTo: 1.3,
        rise: -9,
        duration: 700,
      },
      completeTextStyle: {
        color: "#3e2b22",
      },
    },
    sceneBounds: { x: 902, y: 378, width: 520, height: 430 },
    nextButton: { x: 1095, y: 675 },
    nextButtonLabel: "Siguiente",
  },
  final: {
    rosarito: { x: 1030, y: 468, scale: 0.34, depth: 8 },
    flowers: {
      topLeft: {
        x: 330,
        y: 106,
        key: "ui-flower_cluster_left",
        width: 96,
        height: 62,
        depth: 4,
        angle: -8,
      },
      topRight: {
        x: 465,
        y: 136,
        key: "ui-flower_cluster_bottom",
        width: 94,
        height: 58,
        depth: 4,
      },
      bottom: {
        x: 1090,
        y: 598,
        key: "ui-flower_cluster_bottom",
        width: 94,
        height: 58,
        depth: 9,
      },
    },
    sparkle: {
      x: 1000,
      y: 510,
      key: "ui-icon_sparkles",
      width: 42,
      height: 42,
      depth: 9,
    },
    headingPanel: {
      x: 310,
      y: 132,
      key: "ui-speech_large_lilac",
      width: 430,
      height: 136,
      depth: 5,
      text: {
        x: 310,
        y: 132,
        maxWidth: 360,
        maxHeight: 52,
        minFontSize: 24,
        depth: 6,
        style: {
          fontSize: "34px",
          fontStyle: "bold",
          color: "#6a3d8f",
        },
      },
    },
    bodyPanel: {
      x: 315,
      y: 332,
      key: "ui-speech_large_cream",
      width: 420,
      height: 216,
      depth: 4,
      alpha: 0.95,
      text: {
        x: 315,
        y: 322,
        maxWidth: 330,
        maxHeight: 140,
        minFontSize: 21,
        depth: 5,
        style: {
          fontSize: "27px",
          color: "#3e2b22",
          align: "center",
          wordWrap: { width: 330 },
          lineSpacing: 7,
        },
      },
      divider: {
        x: 315,
        y: 456,
        key: "ui-divider_heart_purple",
        width: 200,
        height: 46,
        depth: 5,
      },
    },
    star: {
      x: 794,
      y: 354,
      key: "ui-star_full",
      width: 236,
      height: 236,
      depth: 5,
      counter: {
        x: 794,
        y: 354,
        text: "{value}/{max}",
        max: 3,
        maxWidth: 124,
        maxHeight: 68,
        minFontSize: 38,
        depth: 6,
        style: {
          fontSize: "62px",
          fontStyle: "bold",
          color: "#3e2b22",
        },
      },
    },
    closing: {
      panel: {
        x: 778,
        y: 590,
        key: "ui-notebook_panel",
        width: 360,
        height: 132,
        depth: 4,
        alpha: 0.98,
      },
      book: {
        x: 642,
        y: 590,
        key: "ui-icon_book",
        width: 84,
        height: 72,
        depth: 5,
      },
      title: {
        x: 792,
        y: 558,
        text: "Álbum de Rosarito",
        maxWidth: 260,
        maxHeight: 48,
        minFontSize: 18,
        depth: 5,
        style: {
          fontSize: "25px",
          fontStyle: "bold",
          color: "#6a3d8f",
        },
      },
      message: {
        x: 800,
        y: 604,
        text: "Gracias por ayudar a recordar su historia.",
        maxWidth: 220,
        maxHeight: 48,
        minFontSize: 16,
        depth: 5,
        style: {
          fontSize: "19px",
          color: "#3e2b22",
          wordWrap: { width: 220 },
        },
      },
    },
    achievementStrip: {
      enabled: true,
      items: [
        { key: "ui-icon_question", x: 690, y: 538, size: 42, depth: 6 },
        { key: "ui-icon_puzzle", x: 776, y: 538, size: 42, depth: 6 },
        { key: "ui-icon_ink", x: 862, y: 538, size: 42, depth: 6 },
      ],
      activeTint: 0x8e5295,
      inactiveTint: 0x9c8c99,
      activeAlpha: 1,
      inactiveAlpha: 0.35,
      checkKey: "ui-icon_check",
      checkSize: 22,
      checkTint: 0x4f8553,
      checkOffsetX: 14,
      checkOffsetY: -16,
      checkAlpha: 0.92,
    },
    text: {
      title: "Objetivos cumplidos",
      body: "Las tres estrellas están encendidas. Rosarito ya completó sus recuerdos, su rompecabezas y sus objetos de enseñanza.",
    },
    restart: {
      x: 975,
      y: 710,
      width: 270,
      label: "Jugar de nuevo",
      targetScene: "Cover",
      depth: 10,
    },
  },
};

window.RosaritoLayouts = { WIDTH, HEIGHT, COLORS, LAYOUT, PAGE_AREAS, SCENE_LAYOUTS };
}());

